name: Docker Image CI

on:
  push:
    branches: [ master ]
    tags:
        - 'v*.*.*'   
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    # extract branch name
    - name: Extract branch name
      if: github.event_name != 'pull_request'
      shell: bash
      run: |
        echo "::set-env name=TAG::$(echo ${GITHUB_REF#refs/*/})"
        docker build . --file Dockerfile --tag mecmus/restic-backup-docker:$TAG --tag mecmus/restic-backup-docker

    # extract branch name on pull request
    - name: Print branch name
      if: github.event_name == 'pull_request'
      run: |
        echo "::set-env name=BRANCH_NAME::$(echo ${GITHUB_HEAD_REF})"
        docker build . --file Dockerfile --tag mecmus/restic-backup-docker:$BRANCH_NAME

    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

    - name: Docker Push
      run: docker push mecmus/restic-backup-docker
