name: Docker Image CI

on:
  push:
    branches: [ master ]
    tags:
        - 'v*.*.*'   
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    # extract branch name
    - name: Extract branch name
      if: github.event_name != 'pull_request'
      shell: bash
      run: docker build . --file Dockerfile --tag ${{secrets.DOCKER_USERNAME}}/restic-backup-docker:${GITHUB_REF#refs/*/} --tag ${{secrets.DOCKER_USERNAME}}/restic-backup-docker

    # extract branch name on pull request
    - name: Print branch name
      if: github.event_name == 'pull_request'
      run: docker build . --file Dockerfile --tag ${{secrets.DOCKER_USERNAME}}/restic-backup-docker:${GITHUB_HEAD_REF}
    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

    - name: Docker Push
      run: docker push mecmus/restic-backup-docker
